name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.0
  - matplotlib=3.11.1
  - networkx=3.2.1
  - scipy=1.17.1
  - powerlaw=1.5
  - openpyxl=3.1.2
  - pyarrow=15.0.0
  - nashpy=0.0.40