#!/usr/bin/env python3
"""
Section 4 - Dynamic network analysis.

Input:
    Existing dynamic_summary.xlsx generated by dynamic_network_experiment_v5.

Default input:
    dynamic_results_150/dynamic_summary.xlsx

Expected conditions:
    static_control_q0.00
    dynamic_q0.10

Each Case1-Case4 table contains:
    Network
    Scenario
    Mean edge turnover
    X final %
    Y final %
    SD final X %
    SD final Y %
    Deviation from Analytical %
    X_only
    Y_only
    coexistence
    coexistence_non_50_50
    mixed_50_50

Rows:
    Baseline static
    Dynamic
    Dynamic minus static

For outcome-count columns, Delta = dynamic count - static count.
No simulation is rerun.
"""

from pathlib import Path
import argparse

import pandas as pd


STATIC_CONDITION = "static_control_q0.00"
DYNAMIC_CONDITION = "dynamic_q0.10"

OUTCOME_CLASSES = [
    "X_only",
    "Y_only",
    "coexistence",
    "coexistence_non_50_50",
    "mixed_50_50",
]


def read_dynamic_summary(
    path: Path,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Read the three sheets required by Section 4."""
    if not path.exists():
        raise FileNotFoundError(path)

    aggregate = pd.read_excel(
        path,
        sheet_name="aggregate_case_results",
    )
    comparison = pd.read_excel(
        path,
        sheet_name="static_dynamic_comparison",
    )
    outcomes = pd.read_excel(
        path,
        sheet_name="outcomes",
    )

    return aggregate, comparison, outcomes


def validate_inputs(
    aggregate: pd.DataFrame,
    comparison: pd.DataFrame,
    outcomes: pd.DataFrame,
) -> None:
    """Validate required source columns."""

    required_aggregate = {
        "network",
        "case",
        "condition",
        "rewiring_rate",
        "total_case_runs",
        "mean_final_X_share",
        "sd_final_X_share",
        "mean_edge_turnover_rate",
        "difference_rate_percent",
    }
    missing = required_aggregate - set(aggregate.columns)
    if missing:
        raise ValueError(
            "aggregate_case_results is missing: "
            f"{sorted(missing)}"
        )

    required_comparison = {
        "network",
        "case",
        "run_seed",
        "condition",
        "change_in_final_X_share",
        "q0_deviates",
        "dynamic_deviates",
    }
    missing = required_comparison - set(comparison.columns)
    if missing:
        raise ValueError(
            "static_dynamic_comparison is missing: "
            f"{sorted(missing)}"
        )

    required_outcomes = {
        "network",
        "case",
        "condition",
        "rewiring_rate",
        "outcome_class",
        "runs",
        "percent",
    }
    missing = required_outcomes - set(outcomes.columns)
    if missing:
        raise ValueError(
            "outcomes is missing: "
            f"{sorted(missing)}"
        )


def outcome_count_dict(
    outcomes: pd.DataFrame,
    network: str,
    case: int,
    condition: str,
    rewiring_rate: float,
    expected_runs: float,
) -> dict[str, float]:
    """
    Return the five outcome counts for one network/case/condition/rate.

    Counts are read directly from the already-aggregated `outcomes` sheet.
    No outcome is reclassified here.

    The lookup includes `rewiring_rate` explicitly so that a workbook
    containing multiple rates cannot be mixed accidentally. The matched
    outcome counts must also sum exactly to `expected_runs` from
    `aggregate_case_results`.
    """
    sub = outcomes[
        (outcomes["network"] == network)
        & (outcomes["case"] == case)
        & (outcomes["condition"] == condition)
        & (
            pd.to_numeric(outcomes["rewiring_rate"], errors="coerce")
            == float(rewiring_rate)
        )
    ].copy()

    if sub.empty:
        raise ValueError(
            "Missing outcomes group for "
            f"network={network}, case={case}, condition={condition}, "
            f"rewiring_rate={rewiring_rate}."
        )

    dupes = sub.duplicated(
        subset=["network", "case", "condition", "rewiring_rate", "outcome_class"],
        keep=False,
    )
    if dupes.any():
        raise ValueError(
            "The outcomes sheet is not unique by "
            "network/case/condition/rewiring_rate/outcome_class for "
            f"network={network}, case={case}, condition={condition}, "
            f"rewiring_rate={rewiring_rate}."
        )

    unexpected = sorted(
        set(sub["outcome_class"].astype(str))
        - set(OUTCOME_CLASSES)
    )
    if unexpected:
        raise ValueError(
            f"Unexpected outcome_class values for network={network}, "
            f"case={case}, condition={condition}, "
            f"rewiring_rate={rewiring_rate}: {unexpected}"
        )

    counts = {outcome: 0.0 for outcome in OUTCOME_CLASSES}
    for _, row in sub.iterrows():
        counts[str(row["outcome_class"])] = float(row["runs"])

    outcome_total = float(sum(counts.values()))
    if outcome_total != float(expected_runs):
        raise ValueError(
            "Incomplete or inconsistent outcomes group for "
            f"network={network}, case={case}, condition={condition}, "
            f"rewiring_rate={rewiring_rate}: outcome counts sum to "
            f"{outcome_total}, but aggregate total_case_runs is "
            f"{float(expected_runs)}."
        )

    return counts


def add_outcome_counts(
    row: dict,
    counts: dict[str, float],
) -> dict:
    """Add the five outcome-count columns to an output row."""
    for outcome in OUTCOME_CLASSES:
        row[outcome] = counts[outcome]
    return row


def build_case_table(
    aggregate: pd.DataFrame,
    comparison: pd.DataFrame,
    outcomes: pd.DataFrame,
    case: int,
) -> pd.DataFrame:
    """Build the Section 4 table for one case."""

    sub = aggregate[aggregate["case"] == case].copy()
    if sub.empty:
        return pd.DataFrame()

    comparison_sub = comparison[
        (comparison["case"] == case)
        & (comparison["condition"] == DYNAMIC_CONDITION)
    ].copy()

    if not comparison_sub.empty:
        dupes = comparison_sub.duplicated(
            subset=["network", "run_seed"],
            keep=False,
        )
        if dupes.any():
            raise ValueError(
                f"Case {case}: static_dynamic_comparison is not unique "
                "by network/run_seed."
            )

    rows = []
    networks = sorted(sub["network"].dropna().unique())

    for network in networks:
        nsub = sub[sub["network"] == network]

        static = nsub[nsub["condition"] == STATIC_CONDITION]
        dynamic = nsub[nsub["condition"] == DYNAMIC_CONDITION]

        if static.empty or dynamic.empty:
            continue

        if len(static) != 1 or len(dynamic) != 1:
            raise ValueError(
                f"Case {case}, network {network}: expected one aggregate "
                "row for each condition."
            )

        static_row = static.iloc[0]
        dynamic_row = dynamic.iloc[0]

        static_counts = outcome_count_dict(
            outcomes=outcomes,
            network=network,
            case=case,
            condition=STATIC_CONDITION,
            rewiring_rate=float(static_row["rewiring_rate"]),
            expected_runs=float(static_row["total_case_runs"]),
        )
        dynamic_counts = outcome_count_dict(
            outcomes=outcomes,
            network=network,
            case=case,
            condition=DYNAMIC_CONDITION,
            rewiring_rate=float(dynamic_row["rewiring_rate"]),
            expected_runs=float(dynamic_row["total_case_runs"]),
        )

        matched = comparison_sub[comparison_sub["network"] == network]

        matched_delta_x = None
        matched_delta_dev = None
        if not matched.empty:
            matched_delta_x = 100.0 * float(
                matched["change_in_final_X_share"].mean()
            )
            matched_delta_dev = 100.0 * float(
                matched["dynamic_deviates"].mean()
                - matched["q0_deviates"].mean()
            )

        base = {"Network": network}

        static_out = base | {
            "Scenario": "Baseline static",
            "Mean edge turnover": float(
                static_row["mean_edge_turnover_rate"]
            ),
            "X final %": 100.0 * float(
                static_row["mean_final_X_share"]
            ),
            "Y final %": 100.0 * (
                1.0 - float(static_row["mean_final_X_share"])
            ),
            "SD final X %": 100.0 * float(
                static_row["sd_final_X_share"]
            ),
            "SD final Y %": 100.0 * float(
                static_row["sd_final_X_share"]
            ),
            "Deviation from Analytical %": float(
                static_row["difference_rate_percent"]
            ),
        }
        add_outcome_counts(static_out, static_counts)

        dynamic_out = base | {
            "Scenario": "Dynamic",
            "Mean edge turnover": float(
                dynamic_row["mean_edge_turnover_rate"]
            ),
            "X final %": 100.0 * float(
                dynamic_row["mean_final_X_share"]
            ),
            "Y final %": 100.0 * (
                1.0 - float(dynamic_row["mean_final_X_share"])
            ),
            "SD final X %": 100.0 * float(
                dynamic_row["sd_final_X_share"]
            ),
            "SD final Y %": 100.0 * float(
                dynamic_row["sd_final_X_share"]
            ),
            "Deviation from Analytical %": float(
                dynamic_row["difference_rate_percent"]
            ),
        }
        add_outcome_counts(dynamic_out, dynamic_counts)

        aggregate_delta_x = (
            dynamic_out["X final %"]
            - static_out["X final %"]
        )
        delta_x = (
            matched_delta_x
            if matched_delta_x is not None
            else aggregate_delta_x
        )

        delta_out = base | {
            "Scenario": "Dynamic minus static",
            "Mean edge turnover": (
                dynamic_out["Mean edge turnover"]
                - static_out["Mean edge turnover"]
            ),
            "X final %": delta_x,
            "Y final %": -delta_x,
            "SD final X %": (
                dynamic_out["SD final X %"]
                - static_out["SD final X %"]
            ),
            "SD final Y %": (
                dynamic_out["SD final Y %"]
                - static_out["SD final Y %"]
            ),
            "Deviation from Analytical %": (
                matched_delta_dev
                if matched_delta_dev is not None
                else (
                    dynamic_out["Deviation from Analytical %"]
                    - static_out["Deviation from Analytical %"]
                )
            ),
        }

        for outcome in OUTCOME_CLASSES:
            delta_out[outcome] = (
                dynamic_out[outcome] - static_out[outcome]
            )

        rows.extend([static_out, dynamic_out, delta_out])

    columns = [
        "Network",
        "Scenario",
        "Mean edge turnover",
        "X final %",
        "Y final %",
        "SD final X %",
        "SD final Y %",
        "Deviation from Analytical %",
        *OUTCOME_CLASSES,
    ]

    return pd.DataFrame(rows, columns=columns)


def build_outcome_validation(
    aggregate: pd.DataFrame,
    outcomes: pd.DataFrame,
) -> pd.DataFrame:
    """
    Validate that outcome counts are complete against aggregate
    `total_case_runs`. Missing groups are explicitly reported.
    """
    rows = []

    aggregate_relevant = aggregate[
        aggregate["condition"].isin(
            [STATIC_CONDITION, DYNAMIC_CONDITION]
        )
    ].copy()

    outcome_relevant = outcomes[
        outcomes["condition"].isin(
            [STATIC_CONDITION, DYNAMIC_CONDITION]
        )
    ].copy()

    expected_group_cols = [
        "network",
        "case",
        "condition",
        "rewiring_rate",
    ]

    # Every aggregate group must have exactly one matching outcome group
    # at the same rewiring rate.
    for _, agg_row in aggregate_relevant.iterrows():
        network = agg_row["network"]
        case = agg_row["case"]
        condition = agg_row["condition"]
        rewiring_rate = float(agg_row["rewiring_rate"])
        expected_runs = float(agg_row["total_case_runs"])

        sub = outcome_relevant[
            (outcome_relevant["network"] == network)
            & (outcome_relevant["case"] == case)
            & (outcome_relevant["condition"] == condition)
            & (
                pd.to_numeric(
                    outcome_relevant["rewiring_rate"],
                    errors="coerce",
                )
                == rewiring_rate
            )
        ].copy()

        unexpected = sorted(
            set(sub["outcome_class"].astype(str))
            - set(OUTCOME_CLASSES)
        )

        valid_runs = float(
            sub[
                sub["outcome_class"].isin(OUTCOME_CLASSES)
            ]["runs"].sum()
        )

        outcome_rows = len(sub)
        outcome_total = float(sub["runs"].sum()) if not sub.empty else 0.0

        status = "OK"
        problems = []

        if sub.empty:
            problems.append("missing outcomes group")
        if unexpected:
            problems.append(
                "unexpected outcome_class=" + ",".join(unexpected)
            )
        if outcome_total != expected_runs:
            problems.append(
                f"all outcome runs={outcome_total:g} != total_case_runs={expected_runs:g}"
            )
        if valid_runs != expected_runs:
            problems.append(
                f"valid outcome runs={valid_runs:g} != total_case_runs={expected_runs:g}"
            )

        if problems:
            status = "CHECK"

        rows.append({
            "network": network,
            "case": case,
            "condition": condition,
            "rewiring_rate": rewiring_rate,
            "aggregate_total_case_runs": expected_runs,
            "outcome_rows": outcome_rows,
            "outcome_runs_total": outcome_total,
            "valid_outcome_runs": valid_runs,
            "difference_vs_aggregate": outcome_total - expected_runs,
            "valid_difference_vs_aggregate": valid_runs - expected_runs,
            "status": status,
            "message": "; ".join(problems) if problems else "OK",
        })

    # Also detect outcome groups that have no aggregate counterpart.
    aggregate_keys = set(
        tuple(row)
        for row in aggregate_relevant[expected_group_cols]
        .itertuples(index=False, name=None)
    )

    for _, group in outcome_relevant.groupby(
        expected_group_cols,
        dropna=False,
    ):
        key = tuple(group[col].iloc[0] for col in expected_group_cols)
        if key in aggregate_keys:
            continue

        rows.append({
            "network": key[0],
            "case": key[1],
            "condition": key[2],
            "rewiring_rate": float(key[3]),
            "aggregate_total_case_runs": 0.0,
            "outcome_rows": len(group),
            "outcome_runs_total": float(group["runs"].sum()),
            "valid_outcome_runs": float(
                group[group["outcome_class"].isin(OUTCOME_CLASSES)]["runs"].sum()
            ),
            "difference_vs_aggregate": float(group["runs"].sum()),
            "valid_difference_vs_aggregate": float(
                group[group["outcome_class"].isin(OUTCOME_CLASSES)]["runs"].sum()
            ),
            "status": "CHECK",
            "message": "outcomes group has no aggregate_case_results counterpart",
        })

    return pd.DataFrame(rows)


def build_delta_validation(
    aggregate: pd.DataFrame,
    comparison: pd.DataFrame,
) -> pd.DataFrame:
    """Validate aggregate X-share deltas against matched-run deltas."""
    rows = []

    for case in [1, 2, 3, 4]:
        networks = sorted(
            aggregate.loc[
                aggregate["case"] == case,
                "network",
            ].dropna().unique()
        )

        for network in networks:
            a = aggregate[
                (aggregate["case"] == case)
                & (aggregate["network"] == network)
            ]

            try:
                sx = float(
                    a.loc[
                        a["condition"] == STATIC_CONDITION,
                        "mean_final_X_share",
                    ].iloc[0]
                )
                dx = float(
                    a.loc[
                        a["condition"] == DYNAMIC_CONDITION,
                        "mean_final_X_share",
                    ].iloc[0]
                )
            except IndexError:
                continue

            m = comparison[
                (comparison["case"] == case)
                & (comparison["network"] == network)
                & (comparison["condition"] == DYNAMIC_CONDITION)
            ]
            if m.empty:
                continue

            aggregate_delta = 100.0 * (dx - sx)
            matched_delta = 100.0 * float(
                m["change_in_final_X_share"].mean()
            )

            rows.append({
                "network": network,
                "case": case,
                "aggregate_delta_X_percent_points": aggregate_delta,
                "matched_run_mean_delta_X_percent_points": matched_delta,
                "difference": aggregate_delta - matched_delta,
            })

    return pd.DataFrame(rows)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Build Section 4 dynamic-network tables from "
            "dynamic_summary.xlsx without rerunning simulations."
        )
    )
    parser.add_argument(
        "--input",
        default="dynamic_results_150/dynamic_summary.xlsx",
        help="Path to dynamic_summary.xlsx",
    )
    parser.add_argument(
        "--outdir",
        default="section4_dynamic_network_analysis",
        help="Output directory",
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    aggregate, comparison, outcomes = read_dynamic_summary(input_path)
    validate_inputs(aggregate, comparison, outcomes)

    tables = {
        f"Case{case}": build_case_table(
            aggregate=aggregate,
            comparison=comparison,
            outcomes=outcomes,
            case=case,
        )
        for case in [1, 2, 3, 4]
    }

    # outcome_validation = build_outcome_validation(outcomes)
    outcome_validation = build_outcome_validation(
        aggregate,
        outcomes,
    )
    delta_validation = build_delta_validation(aggregate, comparison)

    with pd.ExcelWriter(
        outdir / "section4_dynamic_network_analysis.xlsx",
        engine="openpyxl",
    ) as writer:
        for name, table in tables.items():
            table.to_excel(writer, sheet_name=name, index=False)
            table.to_csv(outdir / f"{name}.csv", index=False)

        comparison.to_excel(
            writer,
            sheet_name="matched_static_dynamic",
            index=False,
        )
        outcomes.to_excel(
            writer,
            sheet_name="source_outcomes",
            index=False,
        )
        outcome_validation.to_excel(
            writer,
            sheet_name="outcome_validation",
            index=False,
        )
        delta_validation.to_excel(
            writer,
            sheet_name="delta_validation",
            index=False,
        )

    print(
        "Output workbook:",
        outdir / "section4_dynamic_network_analysis.xlsx",
    )
    print("Tables written: 4")
    print("Outcome-count columns:", ", ".join(OUTCOME_CLASSES))


if __name__ == "__main__":
    main()
